// packages/demo/src/pages/Home.tsx
import { Tabs } from 'antd';
import type React from 'react';
import Formily from './tabs/Formily';
import Introduction from './tabs/Introduction';
import TodoDemo from './tabs/TodoDemo';
import ZustandDemo from './tabs/ZustandDemo';
import './Home.less';

const Home: React.FC = () => {
  return (
    <div className='home'>
      <Tabs
        defaultActiveKey='1'
        items={[
          {
            key: '1',
            label: '项目介绍',
            children: <Introduction />
          },
          {
            key: '2',
            label: '待办事项演示',
            children: <TodoDemo />
          },
          {
            key: '3',
            label: 'Formily 演示',
            children: <Formily />
          },
          {
            key: '4',
            label: 'Zustand 演示',
            children: <ZustandDemo />
          }
        ]}
      />
    </div>
  );
};

export default Home;

// packages/vue3-rsbuild/src/views/Home/index.vue
<template>
  <div class="home">
    <el-tabs v-model="activeKey">
      <el-tab-pane label="项目介绍" name="1">
        <IntroDemo />
      </el-tab-pane>
      <el-tab-pane label="待办事项演示" name="2">
        <TodoDemo />
      </el-tab-pane>
      <el-tab-pane label="Pinia 演示" name="4">
        <PiniaDemo />
      </el-tab-pane>
    </el-tabs>
  </div>
</template>

<script setup lang="ts">
  import IntroDemo from './components/IntroDemo.vue';
  import PiniaDemo from './components/PiniaDemo.vue';
  import TodoDemo from './components/TodoDemo.vue';

  const activeKey = ref('1');
</script>

<style scoped>
  .home {
    padding: 20px;
  }
</style>
